//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo
    {
        public cargo()
        {
            this.obra_colaborador = new HashSet<obra_colaborador>();
        }
    
        public int car_id_cargo { get; set; }
        public string car_ds_cargo { get; set; }
    
        public virtual ICollection<obra_colaborador> obra_colaborador { get; set; }
    }
}
