//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class efetivo_status
    {
        public efetivo_status()
        {
            this.efetivo = new HashSet<efetivo>();
        }
    
        public int est_id_efetivo_status { get; set; }
        public string est_ds_efetivo_status { get; set; }
        public string est_ds_color { get; set; }
    
        public virtual ICollection<efetivo> efetivo { get; set; }
    }
}
