//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipio
    {
        public municipio()
        {
            this.colaborador = new HashSet<colaborador>();
            this.empresa = new HashSet<empresa>();
            this.obra = new HashSet<obra>();
        }
    
        public int mun_id_municipio { get; set; }
        public int mun_id_uf { get; set; }
        public string mun_ds_municipio { get; set; }
    
        public virtual ICollection<colaborador> colaborador { get; set; }
        public virtual ICollection<empresa> empresa { get; set; }
        public virtual uf uf { get; set; }
        public virtual ICollection<obra> obra { get; set; }
    }
}
