//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdo_imagem
    {
        public int rim_id_rdo_imagem { get; set; }
        public int rim_id_rdo { get; set; }
        public int rim_id_imagem { get; set; }
    
        public virtual imagem imagem { get; set; }
        public virtual rdo rdo { get; set; }
    }
}
