//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdo_tarefa
    {
        public int rta_id_rta { get; set; }
        public int rta_id_rdo { get; set; }
        public int rta_id_tarefa { get; set; }
    
        public virtual rdo rdo { get; set; }
        public virtual tarefa tarefa { get; set; }
    }
}
