//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class setor
    {
        public setor()
        {
            this.empresa = new HashSet<empresa>();
        }
    
        public int set_id_setor { get; set; }
        public string set_ds_setor { get; set; }
        public string set_id_setor_loja { get; set; }
    
        public virtual ICollection<empresa> empresa { get; set; }
    }
}
