// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RdoApp.Core.Data.Context;

#nullable disable

namespace RdoApp.Core.Migrations
{
    [DbContext(typeof(RdoContext))]
    partial class RdoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("car_id_cargo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("car_ds_cargo");

                    b.HasKey("Id");

                    b.ToTable("cargo", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("col_id_colaborador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("col_nr_cpf");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("col_dt_insercao");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("col_dt_nascimento");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("col_dt_ultima_atualizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("col_nm_colaborador");

                    b.HasKey("Id");

                    b.ToTable("colaborador", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equ_id_equipamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("equ_ds_equipamento");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("equ_ds_imagem");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("equ_ds_marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("equ_ds_modelo");

                    b.Property<int>("TipoEquipamentoId")
                        .HasColumnType("int")
                        .HasColumnName("equ_id_tipo_equipamento");

                    b.HasKey("Id");

                    b.HasIndex("TipoEquipamentoId");

                    b.ToTable("equipamento", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("eta_id_etapa");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("eta_dt_insercao");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("eta_dt_ultima_atualizacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("eta_ds_etapa");

                    b.Property<int>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("eta_id_obra");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("etapa", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gru_id_grupo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LicencaId")
                        .HasColumnType("int")
                        .HasColumnName("gru_id_licenca");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("gru_id_menu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gru_nm_nome");

                    b.Property<int?>("StatusContratante")
                        .HasColumnType("int")
                        .HasColumnName("gru_st_contratante");

                    b.Property<int?>("StatusDiretor")
                        .HasColumnType("int")
                        .HasColumnName("gru_st_diretor");

                    b.HasKey("Id");

                    b.ToTable("grupo", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Laudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lau_id_laudo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int")
                        .HasColumnName("lau_id_colaborador");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lau_dt_geracao");

                    b.Property<DateTime>("DataLaudo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lau_dt_laudo");

                    b.Property<bool?>("Fundo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lau_tp_fundo");

                    b.Property<bool?>("Limpidez")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lau_tp_limpidez");

                    b.Property<int?>("NivelAlcalinidade")
                        .HasColumnType("int")
                        .HasColumnName("lau_tp_alcalinidade");

                    b.Property<bool?>("NivelBacterias")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lau_tp_nivel_bacterias");

                    b.Property<int?>("NivelCloro")
                        .HasColumnType("int")
                        .HasColumnName("lau_tp_nivel_cloro");

                    b.Property<int?>("NivelPH")
                        .HasColumnType("int")
                        .HasColumnName("lau_tp_ph");

                    b.Property<bool?>("NivelProliferacao")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lau_tp_nivel_proliferacao");

                    b.Property<int>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("lau_id_obra");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("lau_id_status");

                    b.Property<bool?>("Superficie")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lau_tp_superficie");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("ObraId");

                    b.ToTable("laudo", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("obr_id_obra");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("obr_dt_inicio");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("obr_dt_insercao");

                    b.Property<DateTime?>("DataPrevisaoFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("obr_dt_previsao_fim");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("obr_dt_ultima_atualizacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("obr_ds_obra");

                    b.HasKey("Id");

                    b.ToTable("obra", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("oco_id_obra_colaborador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoId")
                        .HasColumnType("int")
                        .HasColumnName("oco_id_cargo");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int")
                        .HasColumnName("oco_id_colaborador");

                    b.Property<DateTime?>("DataContratacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("oco_dt_contratacao");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int")
                        .HasColumnName("oco_id_grupo");

                    b.Property<int>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("oco_id_obra");

                    b.Property<string>("StatusContratanteContratada")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("oco_st_contratante_contratada");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("ObraId");

                    b.ToTable("obra_colaborador", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraEquipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("oeq_id_obra_equipamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("oeq_ds_contato");

                    b.Property<DateTime?>("DataAquisicao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("oeq_dt_aquisicao");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("int")
                        .HasColumnName("oeq_id_equipamento");

                    b.Property<string>("FabricanteFornecedor")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("oeq_ds_fabricante_fornecedor");

                    b.Property<int>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("oeq_id_obra");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("oeq_ds_telefone");

                    b.Property<string>("TipoAquisicao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("oeq_tp_aquisicao");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("ObraId");

                    b.ToTable("obra_equipamento");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraTarefaColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("otc_id_obra_tarefa_colaborador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObraColaboradorId")
                        .HasColumnType("int")
                        .HasColumnName("otc_id_obra_colaborador");

                    b.Property<int>("TarefaId")
                        .HasColumnType("int")
                        .HasColumnName("otc_id_tarefa");

                    b.HasKey("Id");

                    b.HasIndex("ObraColaboradorId");

                    b.HasIndex("TarefaId");

                    b.ToTable("obra_tarefa_colaborador");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraTarefaEquipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ote_id_obra_tarefa_euipamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObraEquipamentoId")
                        .HasColumnType("int")
                        .HasColumnName("ote_id_obra_equipamento");

                    b.Property<int>("TarefaId")
                        .HasColumnType("int")
                        .HasColumnName("ote_id_tarefa");

                    b.HasKey("Id");

                    b.HasIndex("ObraEquipamentoId");

                    b.HasIndex("TarefaId");

                    b.ToTable("obra_tarefa_equipamento");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.StatusTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sta_id_status");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sta_dt_insercao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sta_ds_status");

                    b.HasKey("Id");

                    b.ToTable("status_tarefa", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tar_id_tarefa");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Agrupador")
                        .HasColumnType("char(36)")
                        .HasColumnName("tar_nr_agrupador");

                    b.Property<string>("CodigoParalizacao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tar_codigo_paralizacao");

                    b.Property<int>("ColaboradorInsercaoId")
                        .HasColumnType("int")
                        .HasColumnName("tar_id_colaborador_insercao");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("tar_ds_comentario");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tar_dt_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tar_dt_inicio");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tar_dt_insercao");

                    b.Property<DateTime>("DataMedicao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tar_dt_medicao");

                    b.Property<DateTime?>("DataPrevisaoFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tar_dt_previsao_fim");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("tar_dt_ultima_atualizacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("tar_ds_tarefa");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int")
                        .HasColumnName("tar_id_etapa");

                    b.Property<string>("Foto")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("tar_ds_foto");

                    b.Property<TimeSpan?>("HoraMedicaoFinal")
                        .HasColumnType("time(6)")
                        .HasColumnName("tar_dt_medicao_hora_final");

                    b.Property<TimeSpan?>("HoraMedicaoInicial")
                        .HasColumnType("time(6)")
                        .HasColumnName("tar_dt_medicao_hora_inicial");

                    b.Property<int?>("HorasTrabalhadas")
                        .HasColumnType("int")
                        .HasColumnName("tar_nr_horas_trabalhadas");

                    b.Property<float?>("HorimetroFinal")
                        .HasColumnType("float")
                        .HasColumnName("tar_dt_medicao_horimetro_final");

                    b.Property<float?>("HorimetroInicial")
                        .HasColumnType("float")
                        .HasColumnName("tar_dt_medicao_horimetro_inicial");

                    b.Property<float?>("HorimetroTotal")
                        .HasColumnType("float")
                        .HasColumnName("tar_dt_medicao_horimetro_total");

                    b.Property<float?>("QuantidadeConstruida")
                        .HasColumnType("float")
                        .HasColumnName("tar_nr_qtd_construida");

                    b.Property<decimal?>("QuantidadePrevisao")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tar_nr_qtd_previsao");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("tar_id_status");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int")
                        .HasColumnName("tar_id_unidade");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tar_vl_valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorInsercaoId");

                    b.HasIndex("EtapaId");

                    b.HasIndex("StatusId");

                    b.ToTable("tarefa", (string)null);
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.TipoEquipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("teq_id_tipo_equipamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("teq_ds_tipo_equipamento");

                    b.HasKey("Id");

                    b.ToTable("tipo_equipamento");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Equipamento", b =>
                {
                    b.HasOne("RdoApp.Core.Models.Entities.TipoEquipamento", "TipoEquipamento")
                        .WithMany("Equipamentos")
                        .HasForeignKey("TipoEquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEquipamento");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Etapa", b =>
                {
                    b.HasOne("RdoApp.Core.Models.Entities.Obra", "Obra")
                        .WithMany("Etapas")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Laudo", b =>
                {
                    b.HasOne("RdoApp.Core.Models.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RdoApp.Core.Models.Entities.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraColaborador", b =>
                {
                    b.HasOne("RdoApp.Core.Models.Entities.Cargo", "Cargo")
                        .WithMany("ObraColaboradores")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RdoApp.Core.Models.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RdoApp.Core.Models.Entities.Grupo", "Grupo")
                        .WithMany("ObraColaboradores")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RdoApp.Core.Models.Entities.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Colaborador");

                    b.Navigation("Grupo");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraEquipamento", b =>
                {
                    b.HasOne("RdoApp.Core.Models.Entities.Equipamento", "Equipamento")
                        .WithMany("ObraEquipamentos")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RdoApp.Core.Models.Entities.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraTarefaColaborador", b =>
                {
                    b.HasOne("RdoApp.Core.Models.Entities.ObraColaborador", "ObraColaborador")
                        .WithMany("ObraTarefaColaboradores")
                        .HasForeignKey("ObraColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RdoApp.Core.Models.Entities.Tarefa", "Tarefa")
                        .WithMany("ObraTarefaColaboradores")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraColaborador");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraTarefaEquipamento", b =>
                {
                    b.HasOne("RdoApp.Core.Models.Entities.ObraEquipamento", "ObraEquipamento")
                        .WithMany("ObraTarefaEquipamentos")
                        .HasForeignKey("ObraEquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RdoApp.Core.Models.Entities.Tarefa", "Tarefa")
                        .WithMany("ObraTarefaEquipamentos")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObraEquipamento");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Tarefa", b =>
                {
                    b.HasOne("RdoApp.Core.Models.Entities.Colaborador", "ColaboradorInsercao")
                        .WithMany("Tarefas")
                        .HasForeignKey("ColaboradorInsercaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RdoApp.Core.Models.Entities.Etapa", "Etapa")
                        .WithMany("Tarefas")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RdoApp.Core.Models.Entities.StatusTarefa", "Status")
                        .WithMany("Tarefas")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ColaboradorInsercao");

                    b.Navigation("Etapa");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Cargo", b =>
                {
                    b.Navigation("ObraColaboradores");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Colaborador", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Equipamento", b =>
                {
                    b.Navigation("ObraEquipamentos");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Etapa", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Grupo", b =>
                {
                    b.Navigation("ObraColaboradores");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Obra", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraColaborador", b =>
                {
                    b.Navigation("ObraTarefaColaboradores");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.ObraEquipamento", b =>
                {
                    b.Navigation("ObraTarefaEquipamentos");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.StatusTarefa", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.Tarefa", b =>
                {
                    b.Navigation("ObraTarefaColaboradores");

                    b.Navigation("ObraTarefaEquipamentos");
                });

            modelBuilder.Entity("RdoApp.Core.Models.Entities.TipoEquipamento", b =>
                {
                    b.Navigation("Equipamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
