//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class acidente_colaborador
    {
        public int acc_id_acidente_colaborador { get; set; }
        public int acc_id_acidente { get; set; }
        public int acc_id_obra_colaborador { get; set; }
        public string acc_st_atastamento { get; set; }
    
        public virtual acidente acidente { get; set; }
        public virtual obra_colaborador obra_colaborador { get; set; }
    }
}
