//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class colaborador
    {
        public colaborador()
        {
            this.empresa = new HashSet<empresa>();
            this.obra_colaborador = new HashSet<obra_colaborador>();
            this.obra = new HashSet<obra>();
            this.rdo = new HashSet<rdo>();
            this.tarefa = new HashSet<tarefa>();
        }
    
        public int col_id_colaborador { get; set; }
        public Nullable<int> col_id_municipio { get; set; }
        public string col_nr_cpf { get; set; }
        public string col_nm_colaborador { get; set; }
        public string col_ds_email { get; set; }
        public string col_ds_telefone_principal { get; set; }
        public string col_ds_telefone_secundario { get; set; }
        public string col_ds_foto { get; set; }
        public string col_ds_assinatura { get; set; }
        public string col_ds_senha { get; set; }
        public string col_ds_logradouro { get; set; }
        public string col_ds_bairro { get; set; }
        public string col_ds_numero { get; set; }
        public Nullable<System.DateTime> col_dt_nascimento { get; set; }
        public string col_ds_crea { get; set; }
        public string col_ds_login { get; set; }
        public string col_ds_sexo { get; set; }
        public string col_ds_cep { get; set; }
        public string col_ds_complemento { get; set; }
        public Nullable<bool> col_st_admin { get; set; }
    
        public virtual municipio municipio { get; set; }
        public virtual ICollection<empresa> empresa { get; set; }
        public virtual ICollection<obra_colaborador> obra_colaborador { get; set; }
        public virtual ICollection<obra> obra { get; set; }
        public virtual ICollection<rdo> rdo { get; set; }
        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}
