//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class etapa
    {
        public etapa()
        {
            this.tarefa = new HashSet<tarefa>();
        }
    
        public int eta_id_etapa { get; set; }
        public string eta_ds_etapa { get; set; }
        public int eta_nr_orderm { get; set; }
        public int eta_id_obra { get; set; }
    
        public virtual obra obra { get; set; }
        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}
