//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class laudo
    {
        public int lau_id_laudo { get; set; }
        public int lau_id_status { get; set; }
        public int lau_id_obra { get; set; }
        public System.DateTime lau_dt_laudo { get; set; }
        public string lau_ds_comentario_assinatura { get; set; }
        public Nullable<int> lau_id_colaborador { get; set; }
        public Nullable<System.DateTime> lau_dt_geracao { get; set; }
        public string lau_tp_comentario_assinatura { get; set; }
        public string lau_ds_comentario_geracao { get; set; }
        public string lau_tp_comentario_geracao { get; set; }
        public Nullable<bool> lau_tp_nivel_cloro { get; set; }
        public Nullable<bool> lau_tp_ph { get; set; }
        public Nullable<bool> lau_tp_limpidez { get; set; }
        public Nullable<bool> lau_tp_superficie { get; set; }
        public Nullable<bool> lau_tp_fundo { get; set; }
        public Nullable<bool> lau_tp_nivel_cloro_2 { get; set; }
        public Nullable<bool> lau_tp_nivel_bacterias { get; set; }
        public Nullable<bool> lau_tp_nivel_proliferacao { get; set; }
    }
}
