//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_pagina
    {
        public menu_pagina()
        {
            this.menu_pagina1 = new HashSet<menu_pagina>();
        }
    
        public int mpa_id_menu_pagina { get; set; }
        public int mpa_id_menu { get; set; }
        public int mpa_id_pagina { get; set; }
        public Nullable<int> mpa_id_pagina_pai { get; set; }
        public int mpa_vl_nivel { get; set; }
        public int mpa_vl_ordem { get; set; }
        public string mpa_ds_class { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual ICollection<menu_pagina> menu_pagina1 { get; set; }
        public virtual menu_pagina menu_pagina2 { get; set; }
        public virtual pagina pagina { get; set; }
    }
}
