//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class obra
    {
        public obra()
        {
            this.efetivo = new HashSet<efetivo>();
            this.etapa = new HashSet<etapa>();
            this.obra_colaborador = new HashSet<obra_colaborador>();
            this.obra_equipamento = new HashSet<obra_equipamento>();
            this.rdo = new HashSet<rdo>();
        }
    
        public int obr_id_obra { get; set; }
        public int obr_id_municipio { get; set; }
        public Nullable<int> obr_id_empresa_contratante { get; set; }
        public Nullable<int> obr_id_empresa_contratada { get; set; }
        public Nullable<int> obr_id_dono { get; set; }
        public string obr_ds_obra { get; set; }
        public Nullable<int> obr_nr_area_total { get; set; }
        public Nullable<int> obr_nr_area_total_construida { get; set; }
        public string obr_ds_logradouro { get; set; }
        public string obr_ds_numero { get; set; }
        public string obr_ds_bairro { get; set; }
        public string obr_ds_cep { get; set; }
        public string obr_ds_foto { get; set; }
        public System.DateTime obr_dt_inicio { get; set; }
        public Nullable<System.DateTime> obr_dt_previsao_fim { get; set; }
        public Nullable<System.DateTime> obr_dt_fim { get; set; }
        public Nullable<System.DateTime> obr_dt_vencimento { get; set; }
        public Nullable<int> obr_nr_horas_semana { get; set; }
        public Nullable<int> obr_nr_horas_sabado { get; set; }
        public Nullable<int> obr_nr_horas_domingo { get; set; }
        public string obr_ds_complemento { get; set; }
        public string obr_ds_art { get; set; }
        public Nullable<int> obr_id_colaborador { get; set; }
        public string obr_cd_convite { get; set; }
    
        public virtual colaborador colaborador { get; set; }
        public virtual ICollection<efetivo> efetivo { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual empresa empresa1 { get; set; }
        public virtual empresa empresa2 { get; set; }
        public virtual ICollection<etapa> etapa { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual ICollection<obra_colaborador> obra_colaborador { get; set; }
        public virtual ICollection<obra_equipamento> obra_equipamento { get; set; }
        public virtual ICollection<rdo> rdo { get; set; }
    }
}
