//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class obra_colaborador
    {
        public obra_colaborador()
        {
            this.acidente_colaborador = new HashSet<acidente_colaborador>();
            this.assinatura_rdo = new HashSet<assinatura_rdo>();
            this.efetivo = new HashSet<efetivo>();
            this.historico_tarefa_colaborador = new HashSet<historico_tarefa_colaborador>();
            this.obra_tarefa_colaborador = new HashSet<obra_tarefa_colaborador>();
        }
    
        public int oco_id_obra_colaborador { get; set; }
        public int oco_id_obra { get; set; }
        public int oco_id_colaborador { get; set; }
        public int oco_id_cargo { get; set; }
        public int oco_id_grupo { get; set; }
        public Nullable<System.DateTime> oco_dt_contratacao { get; set; }
        public string oco_st_contratante_contratada { get; set; }
    
        public virtual ICollection<acidente_colaborador> acidente_colaborador { get; set; }
        public virtual ICollection<assinatura_rdo> assinatura_rdo { get; set; }
        public virtual cargo cargo { get; set; }
        public virtual colaborador colaborador { get; set; }
        public virtual ICollection<efetivo> efetivo { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual ICollection<historico_tarefa_colaborador> historico_tarefa_colaborador { get; set; }
        public virtual obra obra { get; set; }
        public virtual ICollection<obra_tarefa_colaborador> obra_tarefa_colaborador { get; set; }
    }
}
