//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagina
    {
        public pagina()
        {
            this.menu_pagina = new HashSet<menu_pagina>();
            this.pagina_acao = new HashSet<pagina_acao>();
        }
    
        public int pag_id_pagina { get; set; }
        public string pag_ds_url { get; set; }
        public string pag_nm_titulo { get; set; }
        public string pag_ds_alias { get; set; }
        public int pag_st_status { get; set; }
    
        public virtual ICollection<menu_pagina> menu_pagina { get; set; }
        public virtual ICollection<pagina_acao> pagina_acao { get; set; }
    }
}
