//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rdoappEntities : DbContext
    {
        public rdoappEntities()
            : base("name=rdoappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<acao> acao { get; set; }
        public DbSet<acidente> acidente { get; set; }
        public DbSet<acidente_colaborador> acidente_colaborador { get; set; }
        public DbSet<assinatura_rdo> assinatura_rdo { get; set; }
        public DbSet<cargo> cargo { get; set; }
        public DbSet<colaborador> colaborador { get; set; }
        public DbSet<efetivo> efetivo { get; set; }
        public DbSet<efetivo_status> efetivo_status { get; set; }
        public DbSet<empresa> empresa { get; set; }
        public DbSet<equipamento> equipamento { get; set; }
        public DbSet<etapa> etapa { get; set; }
        public DbSet<grupo> grupo { get; set; }
        public DbSet<grupo_pagina_acao> grupo_pagina_acao { get; set; }
        public DbSet<historico_tarefa_colaborador> historico_tarefa_colaborador { get; set; }
        public DbSet<historico_tarefa_equipamento> historico_tarefa_equipamento { get; set; }
        public DbSet<historico_tarefa_rdo> historico_tarefa_rdo { get; set; }
        public DbSet<imagem> imagem { get; set; }
        public DbSet<improdutividade> improdutividade { get; set; }
        public DbSet<licenca> licenca { get; set; }
        public DbSet<laudo> laudo { get; set; }
        public DbSet<marca> marca { get; set; }
        public DbSet<menu> menu { get; set; }
        public DbSet<menu_pagina> menu_pagina { get; set; }
        public DbSet<modelo> modelo { get; set; }
        public DbSet<municipio> municipio { get; set; }
        public DbSet<obra> obra { get; set; }
        public DbSet<obra_colaborador> obra_colaborador { get; set; }
        public DbSet<obra_equipamento> obra_equipamento { get; set; }
        public DbSet<obra_tarefa_colaborador> obra_tarefa_colaborador { get; set; }
        public DbSet<obra_tarefa_equipamento> obra_tarefa_equipamento { get; set; }
        public DbSet<pagina> pagina { get; set; }
        public DbSet<pagina_acao> pagina_acao { get; set; }
        public DbSet<parametro> parametro { get; set; }
        public DbSet<perfil_assinante> perfil_assinante { get; set; }
        public DbSet<ramo> ramo { get; set; }
        public DbSet<rdo> rdo { get; set; }
        public DbSet<rdo_imagem> rdo_imagem { get; set; }
        public DbSet<rdo_tarefa> rdo_tarefa { get; set; }
        public DbSet<setor> setor { get; set; }
        public DbSet<status_rdo> status_rdo { get; set; }
        public DbSet<status_tarefa> status_tarefa { get; set; }
        public DbSet<tarefa> tarefa { get; set; }
        public DbSet<tarefa_codigo_paralizacao> tarefa_codigo_paralizacao { get; set; }
        public DbSet<tipo_equipamento> tipo_equipamento { get; set; }
        public DbSet<uf> uf { get; set; }
        public DbSet<unidade_de_medida> unidade_de_medida { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<historico_login> historico_login { get; set; }
    }
}
