//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_tarefa
    {
        public status_tarefa()
        {
            this.historico_tarefa_rdo = new HashSet<historico_tarefa_rdo>();
            this.tarefa = new HashSet<tarefa>();
        }
    
        public int stt_id_status { get; set; }
        public string stt_ds_status { get; set; }
    
        public virtual ICollection<historico_tarefa_rdo> historico_tarefa_rdo { get; set; }
        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}
