//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefa
    {
        public tarefa()
        {
            this.acidente = new HashSet<acidente>();
            this.historico_tarefa_rdo = new HashSet<historico_tarefa_rdo>();
            this.imagem = new HashSet<imagem>();
            this.obra_tarefa_colaborador = new HashSet<obra_tarefa_colaborador>();
            this.obra_tarefa_equipamento = new HashSet<obra_tarefa_equipamento>();
            this.rdo_tarefa = new HashSet<rdo_tarefa>();
        }
    
        public int tar_id_tarefa { get; set; }
        public System.Guid tar_nr_agrupador { get; set; }
        public int tar_id_status { get; set; }
        public int tar_id_etapa { get; set; }
        public Nullable<int> tar_id_unidade { get; set; }
        public string tar_ds_tarefa { get; set; }
        public Nullable<float> tar_nr_qtd_construida { get; set; }
        public System.DateTime tar_dt_inicio { get; set; }
        public Nullable<System.DateTime> tar_dt_previsao_fim { get; set; }
        public Nullable<System.DateTime> tar_dt_fim { get; set; }
        public string tar_ds_comentario { get; set; }
        public string tar_ds_foto { get; set; }
        public Nullable<int> tar_nr_horas_trabalhadas { get; set; }
        public Nullable<System.TimeSpan> tar_dt_medicao_hora_final { get; set; }
        public Nullable<System.TimeSpan> tar_dt_medicao_hora_inicial { get; set; }
        public System.DateTime tar_dt_medicao { get; set; }
        public Nullable<decimal> tar_vl_valor_unitario { get; set; }
        public int tar_id_colaborador_insercao { get; set; }
        public System.DateTime tar_dt_insercao { get; set; }
        public Nullable<System.DateTime> tar_dt_ultima_atualizacao { get; set; }
        public Nullable<decimal> tar_nr_qtd_previsao { get; set; }
        public Nullable<float> tar_dt_medicao_horimetro_total { get; set; }
        public string tar_codigo_paralizacao { get; set; }
        public Nullable<float> tar_dt_medicao_horimetro_inicial { get; set; }
        public Nullable<float> tar_dt_medicao_horimetro_final { get; set; }
    
        public virtual ICollection<acidente> acidente { get; set; }
        public virtual colaborador colaborador { get; set; }
        public virtual etapa etapa { get; set; }
        public virtual ICollection<historico_tarefa_rdo> historico_tarefa_rdo { get; set; }
        public virtual ICollection<imagem> imagem { get; set; }
        public virtual ICollection<obra_tarefa_colaborador> obra_tarefa_colaborador { get; set; }
        public virtual ICollection<obra_tarefa_equipamento> obra_tarefa_equipamento { get; set; }
        public virtual ICollection<rdo_tarefa> rdo_tarefa { get; set; }
        public virtual status_tarefa status_tarefa { get; set; }
        public virtual unidade_de_medida unidade_de_medida { get; set; }
        public virtual tarefa_codigo_paralizacao tarefa_codigo_paralizacao { get; set; }
    }
}
