//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidade_de_medida
    {
        public unidade_de_medida()
        {
            this.tarefa = new HashSet<tarefa>();
        }
    
        public int unm_id_unidade { get; set; }
        public string unm_ds_unidade { get; set; }
        public string unm_ds_simbolo { get; set; }
    
        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}
