//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class acao
    {
        public acao()
        {
            this.pagina_acao = new HashSet<pagina_acao>();
        }
    
        public int aca_id_acao { get; set; }
        public string aca_ds_acao { get; set; }
        public string aca_ds_alias { get; set; }
        public int aca_vl_ordem { get; set; }
    
        public virtual ICollection<pagina_acao> pagina_acao { get; set; }
    }
}
