//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class acidente
    {
        public acidente()
        {
            this.acidente_colaborador = new HashSet<acidente_colaborador>();
        }
    
        public int aci_id_acidente { get; set; }
        public int aci_id_tarefa { get; set; }
        public string aci_ds_acidente { get; set; }
        public Nullable<System.DateTime> aci_dt_data_hora { get; set; }
        public string aci_st_afastamento { get; set; }
    
        public virtual ICollection<acidente_colaborador> acidente_colaborador { get; set; }
        public virtual tarefa tarefa { get; set; }
    }
}
