//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class assinatura_rdo
    {
        public int ass_id_assinatura { get; set; }
        public int ass_id_obra_colaborador_assinante { get; set; }
        public int ass_id_rdo { get; set; }
        public string ass_ds_ip { get; set; }
        public Nullable<System.DateTime> ass_dt_assinatura { get; set; }
    
        public virtual obra_colaborador obra_colaborador { get; set; }
        public virtual rdo rdo { get; set; }
    }
}
