//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class efetivo
    {
        public int efe_id_efetivo { get; set; }
        public int efe_id_obra { get; set; }
        public int efe_id_obra_colaborador { get; set; }
        public int efe_id_efetivo_status { get; set; }
        public System.DateTime efe_data { get; set; }
    
        public virtual obra obra { get; set; }
        public virtual obra_colaborador obra_colaborador { get; set; }
        public virtual efetivo_status efetivo_status { get; set; }
    }
}
