//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipamento
    {
        public equipamento()
        {
            this.obra_equipamento = new HashSet<obra_equipamento>();
        }
    
        public int equ_id_equipamento { get; set; }
        public string equ_ds_equipamento { get; set; }
        public string equ_ds_marca { get; set; }
        public string equ_ds_modelo { get; set; }
        public int equ_id_tipo_equipamento { get; set; }
        public string equ_ds_imagem { get; set; }
    
        public virtual tipo_equipamento tipo_equipamento { get; set; }
        public virtual ICollection<obra_equipamento> obra_equipamento { get; set; }
    }
}
