//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelo
    {
        public int mod_id_modelo { get; set; }
        public string mod_ds_modelo { get; set; }
        public string mod_ds_observacao { get; set; }
    }
}
