//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class obra_tarefa_colaborador
    {
        public int otc_id_obra_tarefa_colaborador { get; set; }
        public int otc_id_obra_colaborador { get; set; }
        public int otc_id_tarefa { get; set; }
    
        public virtual obra_colaborador obra_colaborador { get; set; }
        public virtual tarefa tarefa { get; set; }
    }
}
