//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagina_acao
    {
        public pagina_acao()
        {
            this.grupo_pagina_acao = new HashSet<grupo_pagina_acao>();
        }
    
        public int paa_id_pagina_acao { get; set; }
        public int paa_id_pagina { get; set; }
        public int paa_id_acao { get; set; }
    
        public virtual acao acao { get; set; }
        public virtual ICollection<grupo_pagina_acao> grupo_pagina_acao { get; set; }
        public virtual pagina pagina { get; set; }
    }
}
