//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefa_codigo_paralizacao
    {
        public tarefa_codigo_paralizacao()
        {
            this.tarefa = new HashSet<tarefa>();
        }
    
        public string tarcp_codigo_paralizacao { get; set; }
        public string tarcp_ds_paralizacao { get; set; }
    
        public virtual ICollection<tarefa> tarefa { get; set; }
    }
}
