//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int usu_id_usuario { get; set; }
        public string usu_ds_email { get; set; }
        public string usu_ds_senha { get; set; }
        public int usu_id_grupo { get; set; }
        public Nullable<int> usu_st_status { get; set; }
        public Nullable<int> usu_st_alterar_senha { get; set; }
    
        public virtual grupo grupo { get; set; }
    }
}
