//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public empresa()
        {
            this.obra = new HashSet<obra>();
            this.obra1 = new HashSet<obra>();
            this.obra2 = new HashSet<obra>();
        }
    
        public int emp_id_empresa { get; set; }
        public Nullable<int> emp_id_municipio { get; set; }
        public Nullable<int> emp_id_ramo { get; set; }
        public Nullable<int> emp_id_setor { get; set; }
        public string emp_ds_razao_social { get; set; }
        public string emp_nm_fantasia { get; set; }
        public string emp_nr_cnpj { get; set; }
        public string emp_ds_logradouro { get; set; }
        public string emp_ds_numero { get; set; }
        public string emp_ds_bairro { get; set; }
        public string emp_ds_cep { get; set; }
        public string emp_ds_logo { get; set; }
        public string emp_ds_telefone { get; set; }
        public int emp_id_colaborador { get; set; }
        public string emp_ds_complemento { get; set; }
        public Nullable<int> emp_id_licenca { get; set; }
        public string emp_id_token { get; set; }
    
        public virtual colaborador colaborador { get; set; }
        public virtual ramo ramo { get; set; }
        public virtual setor setor { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual licenca licenca { get; set; }
        public virtual ICollection<obra> obra { get; set; }
        public virtual ICollection<obra> obra1 { get; set; }
        public virtual ICollection<obra> obra2 { get; set; }
    }
}
