//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_pagina_acao
    {
        public int gpa_id_grupo_pagina_acao { get; set; }
        public int gpa_id_grupo { get; set; }
        public int gpa_id_pagina_acao { get; set; }
    
        public virtual grupo grupo { get; set; }
        public virtual pagina_acao pagina_acao { get; set; }
    }
}
