//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.grupo = new HashSet<grupo>();
            this.menu_pagina = new HashSet<menu_pagina>();
        }
    
        public int men_id_menu { get; set; }
        public string men_nm_titulo { get; set; }
        public string men_ds_alias { get; set; }
        public int men_st_status { get; set; }
    
        public virtual ICollection<grupo> grupo { get; set; }
        public virtual ICollection<menu_pagina> menu_pagina { get; set; }
    }
}
