//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class obra_tarefa_equipamento
    {
        public int ote_id_obra_tarefa_euipamento { get; set; }
        public int ote_id_obra_equipamento { get; set; }
        public int ote_id_tarefa { get; set; }
    
        public virtual obra_equipamento obra_equipamento { get; set; }
        public virtual tarefa tarefa { get; set; }
    }
}
