//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil_assinante
    {
        public int per_id_perfil { get; set; }
        public string per_ds_perfil { get; set; }
        public Nullable<int> per_nr_qtd_obras { get; set; }
        public byte[] per_st_acesso_dashboard { get; set; }
        public byte[] per_st_assina_rdo { get; set; }
    }
}
