//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class ramo
    {
        public ramo()
        {
            this.empresa = new HashSet<empresa>();
        }
    
        public int ram_id_ramo { get; set; }
        public string ram_ds_ramo { get; set; }
        public string ram_id_ramo_loja { get; set; }
    
        public virtual ICollection<empresa> empresa { get; set; }
    }
}
