//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdo
    {
        public rdo()
        {
            this.assinatura_rdo = new HashSet<assinatura_rdo>();
            this.historico_tarefa_rdo = new HashSet<historico_tarefa_rdo>();
            this.rdo_imagem = new HashSet<rdo_imagem>();
            this.rdo_tarefa = new HashSet<rdo_tarefa>();
        }
    
        public int rdo_id_rdo { get; set; }
        public int rdo_id_status { get; set; }
        public int rdo_id_obra { get; set; }
        public System.DateTime rdo_dt_rdo { get; set; }
        public string rdo_ds_comentario_assinatura { get; set; }
        public string rdo_ds_clima_manha { get; set; }
        public string rdo_ds_clima_tarde { get; set; }
        public string rdo_ds_clima_noite { get; set; }
        public string rdo_ds_chuva_manha { get; set; }
        public string rdo_ds_chuva_tarde { get; set; }
        public string rdo_ds_chuva_noite { get; set; }
        public Nullable<int> rdo_id_colaborador { get; set; }
        public int rdo_id_improdutividade { get; set; }
        public Nullable<System.DateTime> rdo_dt_geracao { get; set; }
        public string rdo_tp_comentario_assinatura { get; set; }
        public string rdo_ds_comentario_geracao { get; set; }
        public string rdo_tp_comentario_geracao { get; set; }
    
        public virtual ICollection<assinatura_rdo> assinatura_rdo { get; set; }
        public virtual colaborador colaborador { get; set; }
        public virtual ICollection<historico_tarefa_rdo> historico_tarefa_rdo { get; set; }
        public virtual improdutividade improdutividade { get; set; }
        public virtual obra obra { get; set; }
        public virtual status_rdo status_rdo { get; set; }
        public virtual ICollection<rdo_imagem> rdo_imagem { get; set; }
        public virtual ICollection<rdo_tarefa> rdo_tarefa { get; set; }
    }
}
