//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_rdo
    {
        public status_rdo()
        {
            this.rdo = new HashSet<rdo>();
        }
    
        public int str_id_status { get; set; }
        public string str_ds_status { get; set; }
    
        public virtual ICollection<rdo> rdo { get; set; }
    }
}
