//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_equipamento
    {
        public tipo_equipamento()
        {
            this.equipamento = new HashSet<equipamento>();
        }
    
        public int teq_id_tipo_equipamento { get; set; }
        public string teq_nm_tipo_equipamento { get; set; }
        public string teq_ds_tipo_equipamento { get; set; }
    
        public virtual ICollection<equipamento> equipamento { get; set; }
    }
}
