//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdoappClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class uf
    {
        public uf()
        {
            this.municipio = new HashSet<municipio>();
        }
    
        public int ufe_id_uf { get; set; }
        public string ufe_ds_uf { get; set; }
        public string ufe_ds_sigla { get; set; }
    
        public virtual ICollection<municipio> municipio { get; set; }
    }
}
